swallow exceptions

diff --git a/tests/Makefile b/tests/Makefile
--- a/tests/Makefile
+++ b/tests/Makefile
@@ -2,7 +2,7 @@
 .DEFAULT_GOAL := help
 
 # Declare phony targets
-.PHONY: help clean test
+.PHONY: help clean test dev
 
 # Help target
 help:
@@ -40,6 +40,7 @@ define build_and_run
 	@cp .env environments/$(2)/
 	@echo "Building and running Docker container..."
 	@cd environments/$(2) && docker build -t typescript-sdk-$(2) . && docker run --rm --env-file ../../.env typescript-sdk-$(2)
+	@echo "\n----------------------------------------"
 	@echo "Cleaning up Docker image..."
 	@docker rmi typescript-sdk-$(2)
 	@echo "Cleaning up environment..."
@@ -47,6 +48,25 @@ define build_and_run
 		environments/$(2)/honeyhive.tgz \
 		environments/$(2)/Dockerfile \
 		environments/$(2)/.env
+endef
+
+define build_and_run_local
+	@echo "Setting up test environment..."
+	@if [ ! -f honeyhive.tgz ]; then \
+		echo "Building package..." && \
+		cd .. && npm pack && \
+		mv honeyhive-*.tgz tests/honeyhive.tgz && \
+		cd tests; \
+	fi
+	@echo "Copying files to $(2)..."
+	@cp honeyhive.tgz environments/$(2)/
+	@cp .env environments/$(2)/
+	@echo "Installing dependencies and running test locally..."
+	@cd environments/$(2) && \
+		npm install ./honeyhive.tgz --verbose --no-cache && \
+		npm install openai --verbose && \
+		npm install --verbose && \
+		npm run test -- --env-file=.env
 endef
 
 # Test target
@@ -66,9 +86,21 @@ dev:
 		exit 1; \
 	fi
 	@echo "Building package in root directory..."
-	@cd .. && npm run build && cd tests
+	@cd .. && npm run build && rm -f honeyhive*.tgz && cd tests && rm -f honeyhive.tgz
 	$(call extract_and_patch,$(FILE),$(ENV))
 	$(call build_and_run,$(FILE),$(ENV))
+
+local:
+	@if [ -z "$(FILE)" ] || [ -z "$(ENV)" ]; then \
+		echo "Error: Both FILE and ENV must be specified."; \
+		echo "Usage: make test FILE=<test-file> ENV=<environment>"; \
+		exit 1; \
+	fi
+	@echo "Building package in root directory..."
+	@cd .. && npm run build && rm -f honeyhive*.tgz && cd tests && rm -f honeyhive.tgz
+	$(call extract_and_patch,$(FILE),$(ENV))
+	$(call build_and_run_local,$(FILE),$(ENV))
+
 
 # Clean target
 clean:
